application: azoio-apps
module: chatter

version: 1-0-0

runtime: php55
api_version: 1

skip_files:
- ^(.*/)?\..*$
- ^(.*/)?-.*$
- php.ini

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: index.php
